# Generated by Django 5.0.3 on 2024-05-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_name_alter_cost_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Category Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='path/to/default_category_image.jpg', upload_to='category/', verbose_name='Category Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cost', verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price'),
        ),
    ]
